version: '3.5'

services:
    traefik:
        image: traefik:latest
        container_name: "${TRAEFIK_CONTAINER_NAME}"
        command: 
            - "--log.level=${TRAEFIK_LOG_LEVEL}"
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.web.address=:80"
        networks:
            - public
        ports:
            - "${TRAEFIK_HTTP_PORT}:80"
            - "${TRAEFIK_WEB_UI_PORT}:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        restart: "${TRAEFIK_RESTART_POLICY}"

networks:
    public:
        name: "${TRAEFIK_NETWORK_NAME}"
        driver: bridge
