version: '3.2'

services:
    apache:
        container_name: "${COMPOSE_PROJECT_NAME}_apache"
        build:
            context: ./apache
            dockerfile: Dockerfile
            args:
                INSTALL_COMPLETE_TZDATA: "${INSTALL_COMPLETE_TZDATA}"
                APACHE_SYSTEM_PACKAGES: "${APACHE_SYSTEM_PACKAGES}"
                APACHE_MODULES_ENABLED: "${APACHE_MODULES_ENABLED}"
                APACHE_MODULES_DISABLED: "${APACHE_MODULES_DISABLED}"
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=${TRAEFIK_NETWORK_NAME}"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=web"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_PROJECT_NAME}.${TRAEFIK_HOSTNAME}`)"
        networks:
            - private
            - public
        volumes:
            - "./apache/apache2.conf:/etc/apache2/apache2.conf:delegated"
            - "${DOCUMENT_ROOT_HOST_PATH}:${DOCUMENT_ROOT_CONTAINER_PATH}:delegated"
            - "./apache/vhost.conf:/etc/apache2/sites-enabled/000-default.conf:delegated"

    php-fpm:
        container_name: "${COMPOSE_PROJECT_NAME}_php-fpm"
        build:
            context: php-fpm
            dockerfile: Dockerfile
            args:
                INSTALL_COMPLETE_TZDATA: "${INSTALL_COMPLETE_TZDATA}"
                PHP_FPM_VERSION: "${PHP_FPM_VERSION}"
                PHP_FPM_SYSTEM_PACKAGES: "${PHP_FPM_SYSTEM_PACKAGES}"
                PHP_FPM_PEAR_PACKAGES: "${PHP_FPM_PEAR_PACKAGES}"
                PHP_FPM_PECL_PACKAGES: "${PHP_FPM_PECL_PACKAGES}"
                PHP_FPM_COMPOSER_INSTALL: "${PHP_FPM_COMPOSER_INSTALL}"
        depends_on:
            - apache
        networks:
            - private
        volumes:
            - "./php-fpm/xdebug-cli.ini:/etc/php/${PHP_FPM_VERSION}/cli/conf.d/zzzz_xdebug.ini:delegated"
            - "./php-fpm/php-cli.ini:/etc/php/${PHP_FPM_VERSION}/cli/conf.d/zzzz_custom.ini:delegated"
            - "./php-fpm/php.ini:/etc/php/${PHP_FPM_VERSION}/fpm/conf.d/zzzz_custom.ini:delegated"
            - "./php-fpm/php-fpm.conf:/etc/php/${PHP_FPM_VERSION}/fpm/php-fpm.conf:delegated"
            - "${DOCUMENT_ROOT_HOST_PATH}:${DOCUMENT_ROOT_CONTAINER_PATH}:delegated"
            - "./php-fpm/xdebug.ini:/etc/php/${PHP_FPM_VERSION}/fpm/conf.d/zzzz_xdebug.ini:delegated"

    mysql:
        container_name: "${COMPOSE_PROJECT_NAME}_mysql"
        image: "mysql:${MYSQL_VERSION}"
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        networks:
            - private
            - public
        ports:
            - published: "${MYSQL_PUBLISHED_PORT}"
              target: 3306
              protocol: tcp
              mode: host
        volumes:
            - "${MYSQL_DATA_DIR}:/var/lib/mysql"
            - "./mysql/my.cnf:/etc/mysql/my.cnf:delegated"

networks:
    private:
    public:
        external:
            name: "${TRAEFIK_NETWORK_NAME}"
